[build]
command = "pip install --upgrade pip && pip install --no-cache-dir --only-binary=:all: -r requirements.txt && streamlit run app.py"
publish = "."

[build.environment]
PYTHON_VERSION = "3.10"
PIP_NO_CACHE_DIR = "false"
PIP_ONLY_BINARY = ":all:"
